package:
  name: minc-bicpl
  version: "2.0.1"

source:
  #url: https://github.com/BIC-MNI/minc-toolkit-v2/releases/download/release-1.9.18.1/minc-toolkit-v2-1.9.18.1.tar.xz
  #url: https://github.com/BIC-MNI/minc-toolkit-v2/archive/refs/heads/develop-1.9.18-WIP.tar.gz\
  #url:  file:///home/vfonov/src/minc-toolkit-v2-1.9.18.2.tar.gz
  #sha256: c299f6681259626cc5d36051723f2d4411cae8808ac40ef8879a23091e802e65
  #sha256: eda5424f1046dcf39e87b75e8d207edf381318af30228a655ec1c704f4fc8699
  #git_url: https://github.com/BIC-MNI/minc-toolkit-v2.git
  #git_rev: develop-1.9.18
  #path: /home/vfonov/src/minc-toolkit-v2
  #url: https://github.com/BIC-MNI/minc-toolkit-v2/releases/download/release-1.9.18.3/minc-toolkit-v2-1.9.18.3.tar.gz
  #sha256: 824d656af1b5184f896d0265cd41c533e7db4c656a1111a32ca574e666ea313a
  #- path: /home/vfonov/src/minc-toolkit-v2-1.9.18.4/minctools
  #  folder: minctools
  git_url: https://github.com/BIC-MNI/bicpl.git
  git_rev: develop-conda
  #path: /home/vfonov/src/minc-toolkit-v2/bicpl

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - libminc {{ libminc_ver }}
    - hdf5 {{hdf5}} nompi_*
    - libnetcdf {{libnetcdf}} nompi_*
    - netpbm
  # host:
  #   - zlib
  #   - libminc {{ libminc_ver }}
  #   - netpbm
  run:
    - zlib
    - libminc {{ libminc_ver }}
    - netpbm

#test: # TODO?
#   commands:
#     - colour_object -version

build:
  number: 5
  has_prefix_files:
    - lib/BICPLConfig.cmake

about:
  home: http://bic-mni.github.io/
  license: GPL3
  summary: 'bicpl library'
  description: |
    MNI BICPL library.
  doc_url: http://bic-mni.github.io/man-pages
  dev_url: https://github.com/BIC-MNI/bicpl
