context:
  version: 0.6.4

package:
  name: tslearn
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/t/tslearn/tslearn-${{ version }}.tar.gz
    sha256: 9efcd8afe3ef55186f57f4c3ccb45ae353d6f85f7aea2e420032c34a99345705

build:
  script: ${{ PYTHON }} -m pip install --use-pep517 --no-build-isolation . -vv
  noarch: python

requirements:
  host:
    - python
    - setuptools
    - wheel
    - numpy<2.3.0
    - pip
  run:
    - python
    - numpy<2.3.0
    - scipy
    - scikit-learn>=1.3.2,<1.7
    - numba
    - joblib>=0.12
  # - torch  # extra == 'pytorch'
  # - pytest  # extra == 'tests'
  # - torch  # extra == 'tests'

tests:
  - python:
      imports:
        - tslearn
      pip_check: true

about:
  homepage: http://tslearn.readthedocs.io/
  summary: A machine learning toolkit dedicated to time-series data
  license: BSD-2-Clause
