package:
  name: mni_glim_image
  version: "1.1.11"

source:
  path: /home/vfonov/src/minc-toolkit-v2/glim_image

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - mni_libminc {{ libminc_ver }}
  host:
  run:
    - mni_libminc {{ libminc_ver }}


build:
  number: 1
#  string: {{ minctoolkit_variant }}_{{ minctoolkit_visual }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  # force_use_keys:
  #   - hdf5
  #   - libnetcdf
  #   - c_compiler_version
#  run_exports:
#    - {{ pin_compatible('hdf5', max_pin='x.x.x') }}
#    - {{ pin_compatible('libnetcdf', max_pin='x.x') }}
#    - {{ pin_compatible('fftw', max_pin='x.x') }}
#    - openjpeg
#    - zlib
#    - {{ pin_compatible('gsl', max_pin='x.x') }}
#    - jpeg
#    - expat
#    - {{ pin_compatible('openblas', max_pin='x.x') }}            # [minctoolkit_variant == 'openblas'] 

test:
   commands:
     - glim_image -version


about:
  home: http://bic-mni.github.io/
  license: GPL3
  summary: 'MNI voxel-wise GLM analysis'
  description: |
    Voxel-wise GLM analysis
  doc_url: http://bic-mni.github.io/man-pages
  dev_url: https://github.com/BIC-MNI/glim_image
