context:
  version: 0.5.4

build:
  skip:
    - linux-64

package:
  name: antspyx
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/a/antspyx/antspyx-${{ version }}.tar.gz
    sha256: 893e5b45175e278c1e5ab2c4c663f4dbcb08098ee842ba35eca73d785f263749

build:
  script: ${{ PYTHON }} -m pip install .

requirements:
  host:
    - ${{ compiler('cxx') }}
    - python
    - scikit-build-core >=0.4.3
    - nanobind >=1.3.2
    - pip
    - if: linux
      then:
      - libpng
  build:
    - cmake
    - ninja
    - setuptools
    - SimpleITK==2.4.1
  run:
    - python
    - pandas
    - pyyaml
    - numpy <=2.0.1
    - statsmodels
    - webcolors
    - matplotlib
    - pillow
    - requests

tests:
  - python:
      imports:
        - antspyx
      pip_check: false
  - script:
      - bash tests/run_tests.sh
    requirements:
      run:
        - ${{ PYTHON }}
    # extra files to be copied to the test folder from the recipe or source directory
    files:
      source:
        - tests/

about:
  homepage: https://antspyx.readthedocs.io/
  summary: A fast medical imaging analysis library in Python with algorithms for registration, segmentation, and more.
  license: Apache-2.0
