minctoolkit_variant:
  - noblas
#  - legacy
minctoolkit_visual:
  - novisual
#  - full
hdf5: 1.14.0=nompi_hb72d44e_103
libnetcdf: 4.9.2=nompi_h0f3d0bb_105
pin_run_as_build:
    libnetcdf:
      max_pin: x.x
    hdf5:
      max_pin: x.x.x
