context:
  name: dcm2niix
  version: "1.0.20250506"  # Use latest version

package:
  name: ${{ name }}
  version: ${{ version }}


source:
  git: https://github.com/rordenlab/dcm2niix.git
  tag: v${{ version }}

build:
  number: 0
  script: |
    mkdir build
    cd build
    export CFLAGS="$CFLAGS -D_GNU_SOURCE"
    export CXXFLAGS="$CXXFLAGS -D_GNU_SOURCE"
    cmake \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=$PREFIX \
      -DBATCH_VERSION=ON \
      -DUSE_JPEGLS=ON \
      -DUSE_OPENJPEG=ON \
      -DUSE_JASPER=OFF \
      -DUSE_TURBOJPEG=ON \
      -DZLIB_IMPLEMENTATION=Cloudflare \
      -DCMAKE_C_FLAGS="$CFLAGS -D_GNU_SOURCE" \
      -DCMAKE_CXX_FLAGS="$CXXFLAGS -D_GNU_SOURCE" \
      ..
    make -j${CPU_COUNT}
    make install

requirements:
  build:
    - cmake >= 3.16
    - ${{ compiler("cxx") }}
    - pkg-config
    - openjpeg  # For JPEG2000 support
    - charls # For JPEG-LS support
    - libjpeg-turbo  # For JPEG support
    - zlib  # For compression support
  host:
    - libjpeg-turbo  # For JPEG support
  run:
    - libjpeg-turbo  # For JPEG support

tests:
  - script:
    - dcm2niix -h
    - dcm2niibatch ./batch_config.yml
    - dcm2niix | grep -i "JP-LS"  # Verify JPEG-LS support
    files:
      source:
        - batch_config.yml

about:
  homepage: https://github.com/rordenlab/dcm2niix
  license: BSD-2-Clause
  summary: Convert DICOM to NIfTI format with JPEG-LS support
