{% set name = "mni_perllib" %}
{% set version = "0.7.14" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: /home/vfonov/src/minc-toolkit-v2/mni-perllib

build:
  noarch: generic
  number: 2
  run_exports:
    weak:
      - {{ name }} ={{ version }}


requirements:
  build:
    - perl >=5.22
    - make

  run:
    - perl >=5.22

# test:
#   # Perl 'use' tests
#   imports:
#     - MNI::Startup

about:
  home: http://bic-mni.github.io/
  license: GPL3
  summary: 'MNI perl modules.'
  doc_url: http://bic-mni.github.io/man-pages
  dev_url: https://github.com/BIC-MNI/mni-perllib
