libminc_ver:
   - 2.4.06
hdf5: 
#   - 1.10.6 
   - 1.12.2
   - 1.14.3
libnetcdf:
#   - 4.7.4
   - 4.8.1 
   - 4.9.2
zip_keys:
  - hdf5
  - libnetcdf
pin_run_as_build:
    libnetcdf:
      max_pin: x.x
    hdf5:
      max_pin: x.x.x
      min_pin: x.x.x
