package:
  name: mni_ebtks
  version: "1.6.41"

source:
  path: /home/vfonov/src/minc-toolkit-v2/EBTKS

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - mni_libminc {{ libminc_ver }}
    - mni_bicpl
    - mni_arguments
    - pcre
  host:
  run:

# test:
#    commands:
#      - create_lines -help

build:
  number: 1
#  string: {{ minctoolkit_variant }}_{{ minctoolkit_visual }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  # force_use_keys:
  #   - hdf5
  #   - libnetcdf
  #   - c_compiler_version
#  run_exports:
#    - {{ pin_compatible('hdf5', max_pin='x.x.x') }}
#    - {{ pin_compatible('libnetcdf', max_pin='x.x') }}
#    - {{ pin_compatible('fftw', max_pin='x.x') }}
#    - openjpeg
#    - zlib
#    - {{ pin_compatible('gsl', max_pin='x.x') }}
#    - jpeg
#    - expat
#    - {{ pin_compatible('openblas', max_pin='x.x') }}            # [minctoolkit_variant == 'openblas'] 

about:
  home: http://bic-mni.github.io/
  license: GPL3
  summary: 'MNI EBTKS library'
  description: |
    EBTKS library
  doc_url: http://bic-mni.github.io/man-pages
  dev_url: https://github.com/BIC-MNI/EBTKS
