context:
  version: 0.7.2

package:
  name: cmd2
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/c/cmd2/cmd2-${{ version }}.tar.gz
  sha256: d06301cc578a83531261121c0b11d79d29d0a80aca01ed6752c20c4cfcda2dd9

build:
  script: ${{ PYTHON }} -m pip install --use-pep517 --no-build-isolation . -vv
  number: 0

requirements:
  host:
  - python
  - pip
  run:
  - python
  - six
  - pyparsing
  - pygments

tests:
- python:
    imports:
    - cmd2
    pip_check: true

about:
  homepage: https://github.com/python-cmd2/cmd2
  summary: Extra features for standard library's cmd module
  description: |
    cmd2 is an enhancement to the standard library's cmd module for Python 2.7
    and Python 3.3+.   It is pure Python code with dependencies only on the six and pyparsing modules.

    The latest documentation for cmd2 can be read online here:
    https://cmd2.readthedocs.io/

    Drop-in replacement adds several features for command-prompt tools:

        * Searchable command history (commands: "hi", "li", "run")
        * Load commands from file, save to file, edit commands in file
        * Multi-line commands
        * Case-insensitive commands
        * Special-character shortcut commands (beyond cmd's "@" and "!")
        * Settable environment parameters
        * Parsing commands with flags
        * > (filename), >> (filename) redirect output to file
        * < (filename) gets input from file
        * bare >, >>, < redirect to/from paste buffer
        * accepts abbreviated commands when unambiguous
        * `py` enters interactive Python console
        * test apps against sample session transcript (see examples/example.py)

    Usable without modification anywhere cmd is used; simply import cmd2.Cmd in place of cmd.Cmd.
  license: MIT
