name: Build and Upload Conda Packages

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
  pull_request:
    branches:
      - main

# trusted publishing permissions
permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target-platform: linux-64
            build-args: --target-platform linux-64
          - os: ubuntu-24.04-arm
            target-platform: linux-aarch64
            build-args: --target-platform linux-aarch64 # --test skip
          - os: macos-latest
            target-platform: osx-arm64
            build-args: --target-platform osx-arm64

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Authenticate with private channel on repo.prefix.dev
        run: |
          echo '{"repo.prefix.dev": {"CondaToken": "${{ secrets.PREFIX_API_KEY }}"}}' > ${{ runner.temp }}/credentials.json
          echo "RATTLER_AUTH_FILE=${{ runner.temp }}/credentials.json" >> $GITHUB_ENV

      - name: Build individual packages
        shell: bash
        run: |
          rattler-build build --recipe-dir . \
            --skip-existing=all --target-platform=${{ matrix.target }} \
            ${{ matrix.build-args }} --experimental \
            --package-format conda:22 \
            --channel conda-forge \
            --channel https://repo.prefix.dev/nrx-forge

      - name: Upload package
        shell: bash
        # do not upload on PR
        if: github.event_name == 'push'
        run: |
          for pkg in in output/**/*.conda; do
            echo "Uploading ${pkg}"
            rattler-build upload prefix -c nrx-forge "${pkg}"
          done