name: Build and Upload Conda Packages

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
  pull_request:
    branches:
      - main

# trusted publishing permissions
permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   target-platform: linux-64
          #   build-args: --target-platform linux-64
          # - os: ubuntu-24.04-arm
          #   target-platform: linux-aarch64
          #   build-args: --target-platform linux-aarch64 # --test skip
          - os: macos-latest
            target-platform: osx-arm64
            build-args: --target-platform osx-arm64

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.48.1
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_API_KEY }}

      - name: Add .pixi/envs/default/bin to the $PATH
        shell: bash
        run: |
          echo "$(pwd)/.pixi/envs/default/bin" >> $GITHUB_PATH

      - name: Build individual packages
        shell: bash
        run: |
          rattler-build build --recipe-dir . \
            ${{ matrix.build-args }}  \
            --package-format conda:22 \
            --channel conda-forge \
            --channel minc-forge \
            --channel https://repo.prefix.dev/nrx-forge

      - name: Upload package
        shell: bash
        # do not upload on PR
        if: github.event_name == 'push'
        run: |
          for pkg in in output/**/*.conda; do
            echo "Uploading ${pkg}"
            rattler-build upload prefix -c nrx-forge "${pkg}"
          done